# Generated by Django 4.2.2 on 2023-06-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidvaccinecenter',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='covidvaccinecenter',
            name='mobileNum',
            field=models.IntegerField(null=True),
        ),
    ]
