# Generated by Django 4.2.2 on 2023-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_covidvaccinecenter_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidvaccinecenter',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='covidvaccinecenter',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
