# Generated by Django 4.2.2 on 2023-06-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_covidvaccinecenter_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidvaccinecenter',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
