# Generated by Django 4.2.2 on 2023-06-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_covidvaccinecenter_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidvaccinecenter',
            name='email_id',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covidvaccinecenter',
            name='name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
