# Generated by Django 4.2.2 on 2023-06-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_bookings_centeradmin_remove_covidvaccinecenter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidvaccinecenter',
            name='something',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
