# Generated by Django 4.2.2 on 2023-06-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_covidvaccinecenter_something_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidvaccinecenter',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
