# Generated by Django 4.2.2 on 2023-06-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_covidvaccinecenter_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='covidVaccineCenter',
            new_name='userBooking',
        ),
    ]
