# Generated by Django 4.2.2 on 2023-06-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_userbooking_time_alter_userbooking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
