# Generated by Django 4.2.2 on 2023-06-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_userbooking_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='centerAdmin',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='address',
            new_name='center_address',
        ),
    ]
