# Generated by Django 4.2.2 on 2023-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_centeradmin_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationCenters',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('centre_name', models.CharField(max_length=50)),
                ('center_address', models.CharField(max_length=100)),
                ('empty_slots', models.IntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='bookings',
        ),
        migrations.DeleteModel(
            name='center',
        ),
    ]
