# Generated by Django 4.2.2 on 2023-06-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_admindata_vaccinationcenters_delete_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='center_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
