# Generated by Django 4.2.2 on 2023-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_userbooking_center_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcenters',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
